### ISSUE TITLE
HELP WANTED!

### ISSUE THREAD

**Issue by lmangani** [chdb-io/chdb-rust#1]
Are you an open-source enthusiast and Rust developer? Help us turn this binding template into a stable crate!

**Comment by lmangani** [comment]
@alanpaulkwan are you still interested in helping out with this binding?

**Comment by alanpaulkwan** [comment]
I wanted an R binding. It's been a long time and nowadays I don't have much low level programming experience unfortunately.

**Comment by lmangani** [comment]
This is an R binding 😄

**Comment by lmangani** [comment]
@web3creator 👋

**Comment by web3creator** [comment]
@lmangani  This looks like a very early project，I saw the ffi interface inside, which was written manually。I don't know much about c/c++，Are we going to generate rust code based on the c api header file?

**Comment by web3creator** [comment]
@auxten I did not find the c header file of chdb, not c++

**Comment by auxten** [comment]
https://github.com/chdb-io/chdb/blob/main/programs/local/chdb.h

**Comment by lmangani** [comment]
@web3creator if you check out the readme it clearly states this is a (working) experimental FFI binding based on libchdb.so, which I believe answers also your question. If you run the code with the library onboard, you should see how it functions easily.

**Comment by tephrocactus** [comment]
@lmangani @auxten 

Please see [PR](https://github.com/chdb-io/chdb-rust/pull/4).

**Comment by auxten** [comment]
@tephrocactus Thanks for the great work!

**Comment by JakkuSakura** [comment]
I would like to contribute to this, as I will be using this crate in my projects
